### ISSUE TITLE
Support :cached mount flag for improved OSX/Windows performance

### ISSUE THREAD

**Issue by danpoltawski** [danpoltawski/moodle-docker#18]
Since docker  17.06  there is a fix to the Mac performance issues with mounting https://blog.docker.com/2017/05/user-guided-caching-in-docker-for-mac/

Should support this, though I think it might cause compatibility issues with older versions, so need to consider approach

**Comment by stronk7** [comment]
17.06 is already old enough (> 14 days!).

That (change it for everybody and require 17.06)... or consider adding it dynamically to all mounts based on OS guessing + version.

**Comment by danpoltawski** [comment]
It's not clear to me if :cached is only a mac feature, or if all clients support it (and I guess on Linux, ignore it)

**Comment by scara** [comment]
`:cached` has been [released with](https://docs.docker.com/docker-for-mac/osxfs-caching/) 17.04 CE Edge.

That being said, AFAIK is simply ignored where "not supported" but why not playing with overrides for mac only? E.g.:
```
$ docker-compose -f docker-compose.yml -f volumes-cached.yml up
```
HTH,
Matteo

**Comment by danpoltawski** [comment]
I implemented your suggestion @scara, thanks!

For fully phpunit run on my mac:
Before:
```
Time: 1.66 hours, Memory: 372.00MB
```

After:
```
Time: 43.29 minutes, Memory: 372.00MB
```

(Still not that great times, think I can do it natively in 10mins)
